#!/bin/sh

# The user dbus session is shared across all login sessions and all ttys
# Therefore, only tell it about the first wayland session
if [ "$WAYLAND_DISPLAY" = "wayland-1" ]; then
	dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
fi

timestamp=$(date +%F-%R)
$HOME/src/rijan/zig-out/bin/rijan > /tmp/rijan-${timestamp}.log 2>&1 &
openrc --user gui
