colorscheme red-phoenix

set global completers word=all
set global indentwidth 2

# for FreeBSD ports universal-ctags only
set global readtagscmd 'ureadtags'

# show trailing whitespaces of any kind
add-highlighter global/ show-whitespaces -only-trailing -lf ' '
add-highlighter global/ show-matching

# enable back if needed
# TODO file a bug upstream for syntax highlighting issues on macos terminal.app
#add-highlighter global/ruler column 80 default,rgb:222222

#add-highlighter global/relative-linenums number-lines -relative
add-highlighter global/highlight-todos regex \b(TODO|HACK|FIXME|XXX|NOTE)\b 0:+rb

hook global WinSetOption filetype=mail %{
    set window autowrap_column 72
    add-highlighter -override global/ruler column %opt{autowrap_column} default,rgb:444444
    autowrap-enable
}

hook global WinSetOption filetype=bqn %{
    remove-highlighter global/ruler
    remove-highlighter global/relative-linenums
    set window modelinefmt ''
}

hook global BufCreate .+\.(tbf1|skf|FORTH) %{
    set-option buffer filetype forth
}
hook global BufCreate .+\.(dmp|conf) %{
    set-option buffer filetype conf
}

### colemak bindings ###

## hjkl movement
map global normal n j
map global normal N J
map global normal e k
map global normal E K
map global normal i l
map global normal I L
map global normal <c-n> <c-d>
map global normal <c-e> <c-u>

map global normal <a-i> <a-l>

## word/WORD movement
map global normal t e
map global normal T E
map global normal <a-t> <a-e>

## multi-select and insert mode
map global normal s i
map global normal S I
map global normal j s
map global normal J S
map global normal <a-j> <a-s>
map global normal <a-J> <a-S>

## searching
map global normal k n
map global normal K N
map global normal <a-k> <a-n>
map global normal <a-K> <a-N>

## object selection
map global normal <a-r> <a-i>

## goto-mode movement
#map global goto h i
#map global goto H I
map global goto n j
map global goto N J
map global goto e k
map global goto E K
map global goto i l
map global goto I L
map global goto l i
map global goto L I

## view-mode movement
map global view n j
map global view e k
map global view i l

map global insert <c-e> <c-p>
# NOTE needed on FreeBSD where backspace doesn't work in the console
map global insert <c-h> <backspace>

### Siva's convenience mappings ###

map global normal <c-]> :ctags-search<ret>

# case insensitive search by default
map global normal "/" "/(?i)"

# easy way to save file
map global user w :write<ret>

# reformat selection for format=flowed (`fold` is a POSIX tool)
map global user q '|fold -s -w $kak_opt_autowrap_column<ret>'

# quickly delete current buffer and move onto the next one
map global user d :db<ret>:bn<ret>

define-command find -docstring "fuzzy find files" -params 1 %{ edit %arg{1} }
complete-command find shell-script-candidates %{ fd -t f }
map global user f :find<space>

map global user b :buffer<space>
